\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{itb-thesis}
\LoadClass[a4paper,12pt]{report}

% Layout
\setlength{\topmargin}{0pt}
\setlength{\headheight}{0pt}
\setlength{\headsep}{0.46cm}
\setlength{\oddsidemargin}{1.46cm}
\setlength{\evensidemargin}{1.46cm}
\setlength{\textwidth}{14cm}
\setlength{\textheight}{23.7cm}
\setlength{\footskip}{1.5cm}
\setlength{\marginparsep}{0pt}
\setlength{\marginparwidth}{0pt}

% Redefine caption names

%\def\approvalname{HALAMAN PENGESAHAN}

% Define inputan data tesis

% Define cover

% Define abstract in Bahasa

% Define abstract in English

% Define approval page


